version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 15
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 15
    commit-message:
      prefix: "build(deps)"
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 15
    open-pull-requests-limit: 10
    commit-message:
      prefix: "build(deps)"
      prefix-development: "build(deps-dev)"
