FROM ghcr.io/astral-sh/uv:0.11.14@sha256:1025398289b62de8269e70c45b91ffa37c373f38118d7da036fb8bb8efc85d97 AS uv_source

FROM ghcr.io/osgeo/gdal:ubuntu-small-3.10.3@sha256:dab45abca3ca83695d442018692f4f8a0f41955871c57e6101d7f89a92375caa AS builder

COPY --from=uv_source /uv /uvx /bin/

WORKDIR /build

COPY uv.lock pyproject.toml /build/
COPY ./packages/ /build/packages/

ENV UV_PROJECT_ENVIRONMENT=/venv
ENV UV_PYTHON=/usr/bin/python3
ENV UV_PYTHON_PREFERENCE=only-system

RUN uv sync --frozen --no-dev --no-editable --package topo-imagery-raster

FROM ghcr.io/osgeo/gdal:ubuntu-small-3.10.3@sha256:dab45abca3ca83695d442018692f4f8a0f41955871c57e6101d7f89a92375caa

ARG GIT_HASH
ENV GIT_HASH=$GIT_HASH
ARG GIT_VERSION
ENV GIT_VERSION=$GIT_VERSION

COPY --from=builder /venv /venv

ENV PATH="/venv/bin:$PATH"
# TODO: Is this still needed?
ENV GTIFF_SRS_SOURCE="EPSG"

WORKDIR /app
