FROM osgeo/gdal:ubuntu-small-3.6.0

RUN apt-get update
# Install pip
RUN apt-get install python3-pip -y
# Install Poetry
RUN pip install poetry

# Define the working directory for the following commands
#WORKDIR /workspaces/topo-imagery

#ENV PYTHONPATH="/workspaces/topo-imagery"


#WORKDIR /workspaces/topo-imagery/scripts
 