name: Format and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Python "3.10.6"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
      - name: Install
        run: |
          pip install poetry
          poetry install
      - name: Format
        run: |
          poetry run pre-commit run --all-files
      - name: Test
        run: |
          poetry run pytest .

      - name: Build containers
        run: |
          docker build . --tag topo-imagery --label "github_run_id=${GITHUB_RUN_ID}"

      - name: End to end test
        run: |
          # Standardising test - Aerial Imagery
          docker run  -v ${HOME}/tmp/:/tmp/ topo-imagery python3 standardise_validate.py --from-file ./tests/data/aerial.json --preset webp --target-epsg 2193 --source-epsg 2193 --target /tmp/ --collection-id 123 --start-datetime 2023-01-01 --end-datetime 2023-01-01
          cmp --silent ${HOME}/tmp/BG35_1000_4829.tiff ./scripts/tests/data/output/BG35_1000_4829.tiff || exit 1