name: Format and Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Python "3.10.6"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.6"
      - name: Install
        run: |
          pip install poetry
          poetry install
      - name: Format
        run: |
          poetry run pre-commit run --all-files
      - name: Unit Tests
        run: |
          poetry run pytest .

      - name: E2E Tests
        run: |
          poetry run e2e --type all
