name: Format and Tests
on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: topo-imagery
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: "3.12.3"
      - name: Sync uv
        run: |
          uv sync --frozen --no-install-project
      - name: Format
        run: |
          uv run pre-commit run --all-files
      - name: Unit Tests
        run: |
          for pkg in packages/*/; do
            [ -d "${pkg}test" ] || continue
            uv run pytest --doctest-modules "$pkg"
          done

      - name: Build container
        run: |
          docker build --label "github_run_id=${GITHUB_RUN_ID}" --tag "$IMAGE" .

      - name: End to end tests - raster
        run: ./e2e/raster.sh "$IMAGE" "${{ runner.temp }}"

      - name: End to end tests - point cloud
        run: ./e2e/pointcloud.sh "$IMAGE" "${{ runner.temp }}"

      - uses: actions/upload-artifact@v4.6.0
        with:
          name: e2e-output
          path: |
            ${{ runner.temp }}/**/*.tiff
            ${{ runner.temp }}/**/*.geojson
            ${{ runner.temp }}/*.log
          retention-days: 7
          if-no-files-found: ignore
        if: failure()
