on:
  workflow_run:
    workflows: ["Format and Tests"]
    branches: ["master"]
    types:
      - completed

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    environment:
      name: prod
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        id: release
        with:
          token: ${{ secrets.LINZ_GITHUB_AUTOMATION }}

  publish-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      id-token: write
      contents: read
      packages: write
    uses: ./.github/workflows/containers.yml
    secrets: inherit
    with:
      publish: release
